AWSTemplateFormatVersion: "2010-09-09"
Description: "Capture Packets Lambda"
Parameters: 
  ParamStackName: 
    Type: String
    Description: "Name used in resource tags and names"
Resources:
  FireboxSnatLambda:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        S3Bucket: !ImportValue FireboxPrivateBucket
        S3Key: fireboxconfig.zip
      Description: Firebox Lambda to Execute CLI Commands
      Environment:
        Variables:
          Bucket: !ImportValue FireboxPrivateBucket
          FireboxIp: !ImportValue FireboxPrimaryManagementIpAddress
          Key: "firebox-cli-ec2-key.pem"
      FunctionName: CapturePackets
      Handler: packets.capture_packets
      KmsKeyArn: !ImportValue FireboxKmsKeyArn
      MemorySize: 128
      Role: !ImportValue FireboxLambdaCLIRoleArn
      Runtime: python2.7
      Timeout: 90
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue FireboxManagementSecurityGroup
        SubnetIds:
          - !ImportValue FireboxManagementSubnet
      Tags:
        - Key: Name
          Value: FireboxCpaturePacketsLambda
        - Key: Stack
          Value: !Ref ParamStackName