AWSTemplateFormatVersion: 2010-09-09
Description: Firebox Cloud Security Groups

Parameters: 
  ParamStackName: 
    Type: String
    Default: firebox-trial
    Description: Name used in resource tags and names

Resources:

  #Web Server security group associated with Firebox Cloud Web Server ENI
  FireboxWebServerEniSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web Server ENI Firebox Security Group
      SecurityGroupEgress: 
      - CidrIp: "0.0.0.0/0" #anyone can get to the web servers
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      #responses allowed but creating this otherwise the whole world
      #is allowed on every port. Only allowing ephemeral ports for 
      #AWS Linux instances for better security
      #http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_ACLs.html#VPC_ACLs_Ephemeral_Ports
      SecurityGroupIngress:
      - CidrIp: "0.0.0.0/0" #anyone can get to the web servers
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - CidrIp: "0.0.0.0/0" #anyone can get to the web servers
        IpProtocol: udp
        FromPort: 123
        ToPort: 123
      VpcId: !ImportValue FireboxVPC
      Tags:
      - Key: Name
        Value: FireboxWebServerEniSecurityGroup
      - Key: Stack
        Value: 
          Ref: ParamStackName
Outputs:
  FireboxWebServerEniSecurityGroup:
    Value: !Ref FireboxWebServerEniSecurityGroup
    Export:
      Name: FireboxWebServerEniSecurityGroup
