AWSTemplateFormatVersion: 2010-09-09
Description: Firebox Cloud Security Groups

Parameters: 
  ParamStackName: 
    Type: String
    Default: firebox-trial
    Description: Name used in resource tags and names
  ParamCLIPort: 
    Type: String
    Default: 4118
    Description: Open port for CLI access to Firebox on port 4118

Resources:

  #Management security group associated with Firebox Cloud Management ENI
  FireboxManagementEniSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Management ENI Firebox Security Group
      #If no outbound rule is created the whole Internet is allowed
      #by default. 
      SecurityGroupEgress:
        CidrIp: !ImportValue FireboxVPCCidr
        FromPort: !Ref ParamCLIPort
        ToPort: !Ref ParamCLIPort
        IpProtocol: "tcp"
      VpcId: !ImportValue FireboxVPC
      Tags:
      - Key: Name
        Value: FireboxManagementEniSecurityGroup
      - Key: Stack
        Value: 
          Ref: ParamStackName
Outputs:
  FireboxManagementEniSecurityGroup:
    Value: !Ref FireboxManagementEniSecurityGroup
    Export:
      Name: FireboxManagementEniSecurityGroup
  