AWSTemplateFormatVersion: "2010-09-09"
Description: "Packet Capture Server"
Parameters: 
  ParamAmi:
    Type: String
  ParamInstanceType: 
    Type: String
    Default: "t2.micro"
  ParamStackName: 
    Type: String
    Description: "Name used in resource tags and names"
  ParamKeyName: 
    Type: String
    Description: "EC2 Key Pair name for CLI Commands over SSH"
Resources:
  
  PacketServerRoleProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Roles:
        - FireboxLambdaCLIRole
      InstanceProfileName: PacketServerRoleProfile

  PacketCaptureServer:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !Ref ParamAmi
      InstanceType: !Ref ParamInstanceType
      SubnetId: !ImportValue FireboxManagementSubnet
      IamInstanceProfile: !Ref PacketServerRoleProfile
      KeyName: !Ref ParamKeyName
      SecurityGroupIds: 
        - !ImportValue FireboxManagementSecurityGroup
        - !ImportValue S3CidrSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          yum update -y
          version=$(aws --version)
          echo $version
          aws s3 cp s3://firebox-private-cli-bucket-876833387914-us-west-2/firebox-cli-ec2-key.pem /tmp/firebox-cli-ec2-key.pem
          chmod 700 /tmp/firebox-cli-ec2-key.pem
          echo "ssh -i /tmp/firebox-cli-ec2-key.pem admin@52.32.116.182" > /tmp/fb.sh
          echo "tcpdump -x" >> /tmp/fb.sh
          chmod 700 /tmp/fb.sh
          ls /tmp/fb.sh
          ./tmp/fb.sh
          
          #tcpdump -s 0 -x -i eth2 -w /tmp/cap.pcap
      Tags:
        - Key: Name
          Value: PacketCaptureServer
        - Key: Stack
          Value: !Ref ParamStackName
Outputs:
  PacketCaptureServer:
    Value: !Ref PacketCaptureServer
    Export:
      Name: "PacketCaptureServer"
  WebServerIPAddress:
    Value: !GetAtt PacketCaptureServer.PrivateIp
    Export:
      Name: "PacketCaptureServerPrivateIp"
