AWSTemplateFormatVersion: 2010-09-09
Description: Web Server Security Group

Parameters: 

  ParamStackName: 
    Type: String
    Default: firebox-trial
    Description: Name used in resource tags and names

Resources:

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web Server Security Group
      SecurityGroupIngress:
        - SourceSecurityGroupId: !ImportValue FireboxWebServerEniSecurityGroup
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
     
      VpcId: !ImportValue FireboxVPC
      Tags:
        - Key: Name
          Value: WebServerSecurityGroup
        - Key: Stack
          Value: !Ref ParamStackName

Outputs:
  WebServerSecurityGroup:
    Value: !Ref WebServerSecurityGroup
    Export:
      Name: WebServerSecurityGroup
  